name: inshorts_assignment_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  path_provider: ^2.1.5
  intl: ^0.18.0
  dio: ^5.0.2
  logger: ^2.6.0
  retrofit: ^4.6.0
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
